# https://taskfile.dev

version: '3'

tasks:
  default:
    deps: [ build ]
    cmds:
      - task: run-not-use-clone
      - task: run-use-clone
  build:
    cmds:
      - go build -o app main.go
  run-not-use-clone:
    cmds:
      - ./app
  run-use-clone:
    cmds:
      - ./app -use
