# https://github.com/go-task/task
version: '3'

tasks:
  default:
    deps:
      - task: gen
  gen:
    cmds:
      - go run $(go env GOROOT)/src/crypto/tls/generate_cert.go -rsa-bits 2048 -host localhost
  run:
    deps:
      - task: gen
    cmds:
      - go run .