tasks:
  - init: go env -w GO111MODULE=off &&
          go get github.com/cheekybits/genny &&
          go get github.com/devlights/mkghurl &&
          go env -u GO111MODULE &&
          make build &&
          make clean
    command: if [ -n "$GITHUB_TOKEN" ]; then git remote set-url origin $(mkghurl try-golang); fi && go version
image:
  file: .gitpod.Dockerfile
