image: gitpod/workspace-go:latest

tasks:
  - name: prepare
    command: make prepare
  - name: install go-task
    command: brew install go-task/tap/go-task
  - name: show go version
    command: go version

vscode:
  extensions:
    - golang.go
