image: gitpod/workspace-go:latest

tasks:
  - name: install staticcheck
    command: go install honnef.co/go/tools/cmd/staticcheck@latest
  - name: install go-task
    command: brew install go-task/tap/go-task

vscode:
  extensions:
    - golang.go
