tasks:
    - init: >
          cd /workspace &&
          go get golang.org/dl/go1.13.4 &&
          go1.13.4 download &&
          export GOROOT=/home/gitpod/sdk/go1.13.4 &&
          export PATH=${GOROOT}/bin:${PATH} &&
          cd /workspace/try-golang
