image: gitpod/workspace-full:latest

tasks:
  - name: update go version and install tools
    command:
      rm -rf /home/gitpod/tmp &&
      mkdir -p /home/gitpod/tmp &&
      cd /home/gitpod/tmp &&
      wget -q -O go.tar.gz https://go.dev/dl/go1.20.1.linux-amd64.tar.gz &&
      tar zxf go.tar.gz &&
      mv /home/gitpod/go /home/gitpod/go-old &&
      mv go /home/gitpod &&
      go install github.com/go-task/task/v3/cmd/task@latest &&
      go install github.com/go-delve/delve/cmd/dlv@latest &&
      go install honnef.co/go/tools/cmd/staticcheck@latest &&
      go install golang.org/x/tools/cmd/goimports@latest &&
      go install github.com/mgechev/revive@latest &&
      exit

vscode:
  extensions:
    - golang.go
