tasks:
  - init: go env -w GO111MODULE=off &&
          go get -v github.com/cheekybits/genny &&
          go get -v github.com/devlights/mkghurl &&
          go get -v golang.org/dl/go1.14rc1 &&
          go1.14rc1 download &&
          go env -u GO111MODULE &&
          make build &&
          make clean
    command: go version
image:
  file: .gitpod.Dockerfile
