
image: gitpod/workspace-go:latest
tasks:
  - name: prepare
    init: (make prepare; true)
  - name: install go-task
    init: (brew install go-task/tap/go-task; true)
  - name: show go version
    command: go version

vscode:
  extensions:
    - golang.go
