
image:
  file: .gitpod.Dockerfile
tasks:
  - name: prepare
    command: make prepare
  - name: go1.18beta1
    command: >
      go install golang.org/dl/go1.18beta1@latest;
      go1.18beta1 download

vscode:
  extensions:
    - golang.go
