
image: gitpod/workspace-go:latest
tasks:
  - name: prepare
    init: make prepare
  - name: install go-task
    init: brew install go-task/tap/go-task
  - name: show go version
    command: go version

vscode:
  extensions:
    - golang.go
