image:
  file: .gitpod.Dockerfile

tasks:
  - name: initial
    init:
      go install github.com/go-task/task/v3/cmd/task@latest &&
      go install honnef.co/go/tools/cmd/staticcheck@latest &&
      go install golang.org/x/tools/cmd/goimports@latest &&
      go install github.com/mgechev/revive@latest &&
      go build std &&
      task build
    command:
      go version


vscode:
  extensions:
    - golang.go
