# https://github.com/go-task/task
version: "3"

vars:
  APP_NAME: try-golang

includes:
  OS:
    taskfile: ./Taskfile_{{OS}}.yml
    internal: true

tasks:
  default:
    desc: Default (run)
    deps:
      - task: run
  build:
    desc: Build app
    dir: cmd/{{.APP_NAME}}
    cmds:
      - go build -o "{{.ROOT_DIR}}/{{.APP_NAME}}{{exeExt}}" .
  run:
    desc: Run app
    deps: [build]
    cmds:
      - cmd: ./{{.APP_NAME}}{{exeExt}} -onetime
        ignore_error: true
  test:
    desc: Test
    cmds:
      - go test -race -coverprofile /tmp/try-golang-cover $(go list ./... | grep -v /examples/ | grep -v /cmd)
  vet:
    desc: go vet and staticcheck
    cmds:
      - go vet ./...
      - staticcheck ./...
  fmt:
    desc: go fmt
    cmds:
      - go fmt ./...
  clean:
    desc: Clean
    cmds:
      - task: OS:clean
  tags:
    desc: Make tags (Require universal-ctags)
    cmds:
      - ctags -R .
  install-requirements:
    desc: install required libraries
    cmds:
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - go install github.com/go-task/task/v3/cmd/task@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install github.com/mgechev/revive@latest
