version: "3"

tasks:
  default:
    cmds:
      - task: clean
      - task: run
      - task: preview
  clean:
    cmds:
      - rm -f {c.out,c.out.html}
  run:
    cmds:
      - go test -coverprofile c.out .
      - go tool cover -html c.out -o c.out.html
  preview:
    cmds:
      - python3 -m http.server 8888
