# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    cmds:
      - task: build
      - task: debug-gdb
  build:
    cmds:
      - go build -gcflags=all="-N -l" -o app main.go
  debug-gdb:
    cmds:
      - gdb ./app
    interactive: true
  debug-dlv:
    cmds:
      - dlv debug -- "-x" 3
    interactive: true
