version: "3"

tasks:
  build:
    cmds:
      - cd lib ; go build -buildmode=plugin
      - go build -o app
  clean:
    cmds:
      - rm -f ./app
      - find . -name "*.so" | xargs -I{} rm -f {}
  run:
    deps: [build]
    cmds:
      - ./app
  file-tree:
    cmds:
      - find . -print | sed -e "s;[^/]*/;|____;g;s;____|; |;g"
