# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: run-manual
  run-manual:
    cmds:
      - go run main.go
  run-userune:
    cmds:
      - go run main.go -u
  diff:
    cmds:
      - go run main.go > manual.txt
      - go run main.go -u > userune.txt
      - diff manual.txt userune.txt
    ignore_error: true
  clean:
    cmds:
      - rm -f ./*.txt
