# https://taskfile.dev

version: '3'

vars:
  select_object: Select-Object LastAccessTime,LastWriteTime,CreationTime | Format-List
  new_item_cmd: New-Item test.txt -ItemType File -Force | {{.select_object}}
  rm_item_cmd: Remove-Item test.txt -Force
  get_item_cmd: Get-Item test.txt | {{.select_object}}

tasks:
  default:
    cmds:
      - powershell "{{.new_item_cmd}}"
      - defer: powershell "{{.rm_item_cmd}}"
      - go run .
      - powershell "{{.get_item_cmd}}"
