version: "3"

# -------------------------------------------------------------------------------
# $ go help testflag
#
#        -shuffle off,on,N
#            Randomize the execution order of tests and benchmarks.
#            It is off by default. If -shuffle is set to on, then it will seed
#            the randomizer using the system clock. If -shuffle is set to an
#            integer N, then N will be used as the seed value. In both cases,
#            the seed will be reported for reproducibility.
# -------------------------------------------------------------------------------
tasks:
  default:
    cmds:
      - task: run-normal
      - task: run-shuffle
  run-normal:
    cmds:
      - go test -v .
  run-shuffle:
    cmds:
      - go test -v -shuffle on .
