# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  APP: app{{exeExt}}

tasks:
  default:
    cmds:
      # go fix してしまうと go 1.26 の書き方が自動修正されてしまうので、このサンプルでは実行しない
      #- go fix .
      - go vet .
      - go fmt .
      - go build -o {{.APP}} .
      - defer: rm -f {{.APP}}
      - ./{{.APP}}
