# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: build
      - ./app
  build:
    cmds:
      - go build -o app
  clean:
    cmds:
      - rm -f ./app
  doc:
    cmds:
      - go doc -cmd -u -all .
