# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: build
  build:
    cmds:
      - go build
  run:
    deps: [build]
    cmds:
      - ./expvar opt1 opt2 &
      - for i in {1..3} ; do curl -sS http://localhost:8888/debug/vars | jq 'del(.memstats)'; sleep 2; done
      - pgrep expvar | xargs kill
