version: '3'

tasks:
  default:
    cmds:
      - task: run
  install-lib:
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install honnef.co/go/tools/cmd/staticcheck@latest
  build:
    deps: [ install-lib ]
    cmds:
      - goimports -w .
      - go vet
      - staticcheck
      - go build
  run:
    deps: [ build ]
    cmds:
      - ./rss2