version: '3'

tasks:
  default:
    cmds:
      - task: run
  run:
    cmds:
      - task: build-server
      - task: build-client
      - task: start-server
      - task: wait
      - task: run-client
      - task: wait
      - task: kill-server
  build-server:
    dir: server
    cmds:
      - go build
  build-client:
    dir: client
    cmds:
      - go build
  start-server:
    dir: server
    cmds:
      - ./server &
  run-client:
    dir: client
    cmds:
      - ./client
  kill-server:
    cmds:
      - pkill server
  wait:
    cmds:
      - sleep 1
  clean:
    cmds:
      - (cd client; go clean)
      - (cd server; go clean)
      - find . -type f -name "*.PID" -exec rm -rf {} \;