# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    cmds:
      - go build -o app .
      - defer: rm -f app
      - ./app
      - ./app -proc 1
    silent: false
    ignore_error: false
