version: '3'

tasks:
  build:
    cmds:
      - (cd client; go build)
      - (cd server; go build)
  run:
    cmds:
      - task: build
      - task: start-server
      - task: run-client
  start-server:
    cmds:
      - (cd server; ./server)
  run-client:
    cmds:
      - (cd client; ./client)
  kill-server:
    cmds:
      - pkill server
  clean:
    cmds:
      - (cd client; go clean)
      - (cd server; go clean)
      - find . -type f -name "*.PID" -exec rm -rf {} \;