version: '3'

tasks:
  default:
    cmds:
      - go build -o server main.go
      - ./server &
      - sleep 1
      - curl http://localhost:8888/
      - curl http://localhost:8888/something
      - kill -INT $(pgrep server)