# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: clean
      - task: build
      - task: run
  clean:
    cmds:
      - rm -f ./app
  build:
    cmds:
      - go build -o app .
  run:
    cmds:
      - ./app
      - unzip -l archive.zip